### ISSUE TITLE
Additional labels from array value

### ISSUE THREAD

**Issue by krasish** [neo4j/graphql#2054]
**Is your feature request related to a problem? Please describe.**
Hi there! 👋 I am trying to use the @node directive for setting labels from jwt values ( introduced with #536 ). It works fine for string values and already does a great job for me but I was wondering if we could possibly introduce handling of array values. 

**A clear and concise description of what the problem is.**

The problem is that, if for example, I have the following type

```graphql
type TwoDPoint
  @node(additionalLabels: ["$jwt.namespaces"]) {
  id: ID!
  name: String!
  createdAt: Timestamp!

  x: Int
  y: Int
}
```
... and I try to create a **TwoDPoint** with a token which has payload something like this:
```json
{
   ...
  "namespaces": ["foo", "bar"],
   ...
}
```

I would get an error saying that `label.replace is not a function`. As far as I can see, the current implementation simply does not support array values in jwt payload but I believe that such functionality could be useful in other scenarios as well. 

**Describe the solution you'd like**

In the above scenario, I would expect to end with a node in the database that has labels `["TwoDPoint", "foo", "bar"]`. 

**Describe alternatives you've considered**

Alternatively, there could be something like a separator character for the specified string value. For example for a type like

```graphql
type TwoDPoint
  @node(additionalLabels: ["$jwt.namespaces", separator: " "]) {
  id: ID!
  name: String!
  createdAt: Timestamp!

  x: Int
  y: Int
}
``` 

... and a token with payload like

```json
{
   ...
  "namespaces": "foo bar",
   ...
}
```

I would expect to end with a node in the database that has labels `["TwoDPoint", "foo", "bar"]`. 

Thanks in advance for looking through this FR! 🙏

**Comment by darrellwarde** [comment]
This is a tricky problem! From your example:

> ```graphql
> type TwoDPoint
>   @node(additionalLabels: ["$jwt.namespaces"]) {
>   id: ID!
>   name: String!
>   createdAt: Timestamp!
> 
>   x: Int
>   y: Int
> }
> ```

What would happen if we added an additional label:

> ```graphql
> type TwoDPoint
>   @node(additionalLabels: ["$jwt.namespaces", "additional"]) {
>   id: ID!
>   name: String!
>   createdAt: Timestamp!
> 
>   x: Int
>   y: Int
> }
> ```

We're then in this situation where what looks like an array with two elements is suddenly expanded to three, which I think is a confusing behaviour.

I'm torn between closing this as a "won't do", or agreeing on a middle ground where if `additionalLabels` only has one element which refers to a JWT or context value, then check whether it is an array and evaluate as appropriate. But this also feels somewhat like a hack.

**Comment by aibps** [comment]
There is one case that we have two dynamic labels: `$context.label1`, `$context.label2` which are from the context. when condition 1 is true, we set label1 and label2, but when condition 2 is true, we should only set label1 and not set label2. In the last case  there will be an error from the code in `NodeDirective`:
```
const mappedLabel = ContextParser.getProperty(ctxPath, context);
if (!mappedLabel) throw new Error(`Label value not found in context.`);
```
May be the last case can be supported by `$context.namespaces` above?

**Comment by darrellwarde** [comment]
`additionalLabels` was never intended for complex logic. We're not going to add spreading of array values or conditional inclusion as has been asked for here.
